// seed.js
require('dotenv').config();
const { createKysely } = require('@vercel/kv');

const db = createKysely();

async function seedDatabase() {
    console.log("Starting to seed database with the full ARI question bank...");

    const questionBank = {
        phase1: [
            { id: 'p1_01', scenario: "Your team's project has stalled due to internal disagreements.", options: [{text:"Re-focus everyone on the objective and push for a decision to get moving.", domain: 'praxis'}, {text:"Organize a workshop to let everyone voice concerns and build consensus.", domain: 'nexus'}, {text:"Analyze the project data to present a logical case for the best path forward.", domain: 'cognito'}] },
            { id: 'p1_02', scenario: "You are tasked with improving efficiency in your department.", options: [{text:"Take decisive action to remove obvious bottlenecks immediately.", domain: 'praxis'}, {text:"Mediate between teams to improve collaboration and workflows.", domain: 'nexus'}, {text:"Implement a strict, new set of procedures for everyone to follow.", domain: 'kosmos'}] },
            { id: 'p1_03', scenario: "A new, disruptive technology emerges in your field.", options: [{text:"Take immediate steps to integrate the technology into a current project.", domain: 'praxis'}, {text:"Facilitate brainstorming sessions on how this technology changes your team's purpose.", domain: 'nexus'}, {text:"Start experimenting with the technology to create something entirely new.", domain: 'genesis'}] },
            { id: 'p1_04', scenario: "A critical project is falling behind schedule.", options: [{text:"Assume direct control and make rapid decisions to get back on track.", domain: 'praxis'}, {text:"Research the root cause of the delays to form a long-term strategy.", domain: 'cognito'}, {text:"Audit the project against its original plan to enforce deadlines and procedures.", domain: 'kosmos'}] },
            { id: 'p1_05', scenario: "You have an idea for a radical new product.", options: [{text:"Immediately start building a prototype to prove its viability.", domain: 'praxis'}, {text:"Conduct deep market research to validate the idea's potential.", domain: 'cognito'}, {text:"Embrace the creative process and start designing its aesthetic and function.", domain: 'genesis'}] },
            { id: 'p1_06', scenario: "You must design a new public park.", options: [{text:"Lead construction efforts, focusing on getting it built quickly and efficiently.", domain: 'praxis'}, {text:"Establish a clear set of rules for park use and a fair maintenance schedule.", domain: 'kosmos'}, {text:"Envision a unique, artistic park design that breaks conventions.", domain: 'genesis'}] },
            { id: 'p1_07', scenario: "Your team is launching a new internal tool.", options: [{text:"Host workshops to ensure everyone feels comfortable and connected with the tool.", domain: 'nexus'}, {text:"Develop a deep understanding of the tool's technical capabilities and limitations.", domain: 'cognito'}, {text:"Create a comprehensive user manual and a strict rollout schedule.", domain: 'kosmos'}] },
            { id: 'p1_08', scenario: "A community project needs a leader.", options: [{text:"Focus on fostering a positive, collaborative spirit among volunteers.", domain: 'nexus'}, {text:"Research the community's history and needs to create an informed plan.", domain: 'cognito'}, {text:"Design an innovative project that will capture the community's imagination.", domain: 'genesis'}] },
            { id: 'p1_09', scenario: "You are asked to plan a major event.", options: [{text:"Focus on networking and making sure all attendees feel connected.", domain: 'nexus'}, {text:"Create a meticulous schedule and a clear set of rules for all participants.", domain: 'kosmos'}, {text:"Design a unique theme and a series of unexpected, creative experiences.", domain: 'genesis'}] },
            { id: 'p1_10', scenario: "A complex problem has no obvious solution.", options: [{text:"Gather all available data and model different outcomes before acting.", domain: 'cognito'}, {text:"Create a strict, methodical process for the team to follow to ensure nothing is missed.", domain: 'kosmos'}, {text:"Challenge all assumptions and begin brainstorming radical, new possibilities.", domain: 'genesis'}] },
        ],
        phase2: [
            { id: 'p2_01', scenario: "A team member is underperforming.", options: [{text:"Address the issue directly, focusing on results.", domain: 'praxis'}, {text:"Talk with them privately to understand.", domain: 'nexus'}, {text:"Analyze their performance metrics.", domain: 'cognito'}, {text:"Refer to the official procedure.", domain: 'kosmos'}, {text:"Suggest a radical new role for them.", domain: 'genesis'}] },
            { id: 'p2_02', scenario: "You need to create a new team from scratch.", options: [{text:"Select members for their ability to deliver results.", domain: 'praxis'}, {text:"Choose people who will form a harmonious group.", domain: 'nexus'}, {text:"Pick the most skilled expert for each role.", domain: 'cognito'}, {text:"Assign roles based on an organizational chart.", domain: 'kosmos'}, {text:"Assemble a team of diverse thinkers who will challenge each other.", domain: 'genesis'}] },
            { id: 'p2_03', scenario: "Your organization needs a new slogan.", options: [{text:"Push for a bold slogan that calls people to action.", domain: 'praxis'}, {text:"Organize focus groups to find a slogan that resonates.", domain: 'nexus'}, {text:"Analyze market data to craft an effective slogan.", domain: 'cognito'}, {text:"Ensure the slogan adheres to all brand guidelines.", domain: 'kosmos'}, {text:"Create an artistic and unconventional slogan.", domain: 'genesis'}] },
            { id: 'p2_04', scenario: "A project budget needs to be cut by 20%.", options: [{text:"Make swift, executive decisions on cuts.", domain: 'praxis'}, {text:"Hold a team meeting to decide on cuts collaboratively.", domain: 'nexus'}, {text:"Conduct analysis to find cuts with least impact.", domain: 'cognito'}, {text:"Enforce across-the-board cuts based on rules.", domain: 'kosmos'}, {text:"Re-imagine the project's scope to fit the budget.", domain: 'genesis'}] },
            { id: 'p2_05', scenario: "You have a free weekend for a personal project.", options: [{text:"Build something practical and useful.", domain: 'praxis'}, {text:"Spend time strengthening bonds with family/friends.", domain: 'nexus'}, {text:"Learn a new complex skill or read non-fiction.", domain: 'cognito'}, {text:"Tidy and organize your living space.", domain: 'kosmos'}, {text:"Write a story, paint, or compose music.", domain: 'genesis'}] },
            { id: 'p2_06', scenario: "Your city is debating a new law.", options: [{text:"Organize a rally to push for your desired outcome.", domain: 'praxis'}, {text:"Facilitate town halls to foster understanding.", domain: 'nexus'}, {text:"Research the law's potential economic/social impacts.", domain: 'cognito'}, {text:"Ensure the law is written clearly and fairly.", domain: 'kosmos'}, {text:"Propose a creative, alternative solution.", domain: 'genesis'}] },
            { id: 'p2_07', scenario: "A junior colleague asks for mentorship.", options: [{text:"Give them a challenging task to test their capabilities.", domain: 'praxis'}, {text:"Focus on building their network and confidence.", domain: 'nexus'}, {text:"Provide them with resources to deepen their knowledge.", domain: 'cognito'}, {text:"Help them create a structured career plan.", domain: 'kosmos'}, {text:"Encourage them to pursue a unique passion project.", domain: 'genesis'}] },
            { id: 'p2_08', scenario: "You discover a hidden talent.", options: [{text:"Use this talent to achieve a measurable goal.", domain: 'praxis'}, {text:"Use this talent to connect with and help others.", domain: 'nexus'}, {text:"Study the theory and history of this talent.", domain: 'cognito'}, {text:"Develop a disciplined practice schedule to perfect it.", domain: 'kosmos'}, {text:"Use it as a form of pure self-expression.", domain: 'genesis'}] },
            { id: 'p2_09', scenario: "A family vacation needs planning.", options: [{text:"Plan a trip packed with activities and challenges.", domain: 'praxis'}, {text:"Ensure everyone's desires are heard for a harmonious trip.", domain: 'nexus'}, {text:"Research the history and culture of the destination.", domain: 'cognito'}, {text:"Create a detailed itinerary and budget.", domain: 'kosmos'}, {text:"Plan an adventurous, spontaneous trip.", domain: 'genesis'}] },
            { id: 'p2_10', scenario: "The Internet goes down and you are bored.", options: [{text:"Do a home workout or physical project.", domain: 'praxis'}, {text:"Call a friend to chat.", domain: 'nexus'}, {text:"Work through logic puzzles.", domain: 'cognito'}, {text:"Organize a messy part of your house.", domain: 'kosmos'}, {text:"Start writing or sketching.", domain: 'genesis'}] }
        ],
        phase3: {
            praxis: Array.from({length: 10}).map((_, i) => ({ id: `p3_px_${i+1}`, scenario: `Praxis Scenario ${i+1}: When faced with a roadblock, you...`, options: [{text: `Commander approach ${i+1}`, archetype: "commander"}, {text: `Executor approach ${i+1}`, archetype: "executor"}, {text: `Finisher approach ${i+1}`, archetype: "finisher"}, {text: `Gladiator approach ${i+1}`, archetype: "gladiator"}] })),
            cognito: Array.from({length: 10}).map((_, i) => ({ id: `p3_co_${i+1}`, scenario: `Cognito Scenario ${i+1}: When presented with new information, you...`, options: [{text: `Strategist approach ${i+1}`, archetype: "strategist"}, {text: `Scholar approach ${i+1}`, archetype: "scholar"}, {text: `Analyst approach ${i+1}`, archetype: "analyst"}, {text: `Sage approach ${i+1}`, archetype: "sage"}] })),
            nexus: Array.from({length: 10}).map((_, i) => ({ id: `p3_nx_${i+1}`, scenario: `Nexus Scenario ${i+1}: To build a strong team, you...`, options: [{text: `Ambassador approach ${i+1}`, archetype: "ambassador"}, {text: `Empath approach ${i+1}`, archetype: "empath"}, {text: `Steward approach ${i+1}`, archetype: "steward"}, {text: `Mobilizer approach ${i+1}`, archetype: "mobilizer"}] })),
            kosmos: Array.from({length: 10}).map((_, i) => ({ id: `p3_ko_${i+1}`, scenario: `Kosmos Scenario ${i+1}: When designing a process, you prioritize...`, options: [{text: `Architect approach ${i+1}`, archetype: "architect"}, {text: `Judge approach ${i+1}`, archetype: "judge"}, {text: `Curator approach ${i+1}`, archetype: "curator"}, {text: `Guardian approach ${i+1}`, archetype: "guardian"}] })),
            genesis: Array.from({length: 10}).map((_, i) => ({ id: `p3_ge_${i+1}`, scenario: `Genesis Scenario ${i+1}: Your creative process involves...`, options: [{text: `Pioneer approach ${i+1}`, archetype: "pioneer"}, {text: `Artisan approach ${i+1}`, archetype: "artisan"}, {text: `Provocateur approach ${i+1}`, archetype: "provocateur"}, {text: `Catalyst approach ${i+1}`, archetype: "catalyst"}] }))
        }
    };

    await db.set('ari-question-bank', questionBank);
    console.log("Database seeded successfully!");
}

seedDatabase();
